// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "absurder-sql.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "NativeAbsurderSql.h"

@interface AbsurderSql : NSObject <NativeAbsurderSqlSpec>
#else
#import <React/RCTBridgeModule.h>

@interface AbsurderSql : NSObject <RCTBridgeModule>
#endif

@end