require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '18.4'
prepare_react_native_project!

target 'AbsurderSQLTests' do
  use_react_native!
end

post_install do |installer|
  react_native_post_install(
    installer,
    '../node_modules/react-native'
  )
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '18.4'
    end
  end
end
