# Cargo configuration for mobile builds

[target.aarch64-linux-android]
linker = "aarch64-linux-android21-clang"
ar = "llvm-ar"
rustflags = ["-C", "relocation-model=pic", "-L", "native=absurder-sql-mobile/android/src/main/jni/sqlcipher-libs/arm64-v8a"]

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi21-clang"
ar = "llvm-ar"
rustflags = ["-C", "relocation-model=pic", "-L", "native=absurder-sql-mobile/android/src/main/jni/sqlcipher-libs/armeabi-v7a"]

[target.i686-linux-android]
linker = "i686-linux-android21-clang"
ar = "llvm-ar"
rustflags = ["-C", "relocation-model=pic", "-L", "native=absurder-sql-mobile/android/src/main/jni/sqlcipher-libs/x86"]

[target.x86_64-linux-android]
linker = "x86_64-linux-android21-clang"
ar = "llvm-ar"
rustflags = ["-C", "relocation-model=pic", "-L", "native=absurder-sql-mobile/android/src/main/jni/sqlcipher-libs/x86_64"]
